### ISSUE TITLE
Handle user's orders with server's API calls

### ISSUE THREAD

**Issue by chapluck** [saxarkompot/make-me-dinner#10]
You need to call server's API every time a user orders some dishes or decreases number of ordered dishes.
Every time a user increases a number of ordered dishes call:
```
POST http://localhost:3001/users/me/orders
content-type: application/json

{
"dishId" :  dishIdHere
}
```

Every time a user decreases a number of ordered dishes call:
```
DELETE http://localhost:3001/users/me/orders
content-type: application/json

{
"dishId" :  dishIdHere
}
```

Once a page is loaded we need to show an actual numbers of ordered dishes as well as a correct sum in the cart.
To get all actual orders of a user make a call:
GET http://localhost:3001/users/me/orders

**Comment by saxarkompot** [comment]
It was made in the branch "mmd-8"
